### ISSUE TITLE
Release balas include SNAPSHOT jars

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/module-ballerina-observe#39]
**Description:**
$subject

**Comment by nadundesilva** [comment]
The released version's Jars does not contains the snapshots now.

![Screenshot 2022-05-31 at 11 15 36 AM](https://user-images.githubusercontent.com/10029121/171101351-db3f4e67-997f-404b-8a94-7de33b5c94ec.png)

Hence closing the issue.
